name: Release package

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"

      - uses: oven-sh/setup-bun@v2

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        id: bun-install
        run: bun install

      - name: Build
        id: ts-build
        run: bun run build

      - name: Publish
        id: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
